kind: project
metadata:
  name: pii-pengwei
spec:
  functions: []
  workflows: []
  artifacts: []
  conda: ''
  source: git@github.com-personal:pengwei715/pii_masker.git#refs/heads/main
  origin_url: git@github.com-personal:pengwei715/pii_masker.git#refs/heads/main
  desired_state: online
