kind: project
metadata:
  name: pii-pengwei
  created: '2023-07-05T19:42:41.415000'
spec:
  functions:
  - url: process.py
    name: process
    kind: job
    image: mlrun/ml-models
    handler: process
    with_repo: true
    requirements:
    - pandas
    - streamlit
    - presidio-anonymizer
    - presidio-analyzer
    - torch
    - flair@git+https://github.com/flairNLP/flair.git@d4ed67bf663e4066517f00397412510d90043653
    - st-annotated-text
    - https://huggingface.co/beki/en_spacy_pii_distilbert/resolve/main/en_spacy_pii_distilbert-any-py3-none-any.whl
  workflows: []
  artifacts: []
  conda: ''
  source: https://github.com/pengwei715/pii_masker
  load_source_on_run: true
  desired_state: online
  owner: PengWei
  default_image: mlrun/ml-models
status:
  state: online
